- name: Check connection from web to postgres on db server
  wait_for:
    port: 5432
    host: "{{ db_ip }}"
    timeout: 60

- name: Check connection from web to redis on db server
  wait_for:
    port: 6379
    host: "{{ db_ip }}"
    timeout: 60

- name: Install web role
  command: "bash {{ tempdir.path }}/kasm_release/install.sh -S app -e -L {{ proxy_port }} -q {{ db_ip }} -Q {{ database_password }} -R {{ redis_password }} -n {{ target_ip }} {{ '-s ' ~ service_images_copy.dest if service_images_file }} {{ '-w ' ~ workspace_images_copy.dest if workspace_images_file }}"
  register: install_output
  become: true
  retries: 20
  delay: 10
  until: install_output is success or ('Failed to lock apt for exclusive operation' not in install_output.stderr and '/var/lib/dpkg/lock' not in install_output.stderr)
